name: BendingPermissions
author: Jacksonnn
version: BETA v1.0
main: com.jacksonnn.BendingPermissions.BendingPermissions
commands:
  bendingpermissions:
    aliases: [bp, bperm, bendingp]
    usage: /<command>
    description: Simple solution to keeping track of your ProjectKorra permissions!
